version: "3.7"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    restart: always
    volumes:
      - $PWD/volume/mysql/data:/var/lib/mysql
    ports:
      - "3390:3306"
    environment:
      - MYSQL_DATABASE=b3teste
      - MYSQL_USER=leandro
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_VERSION=latest
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 100s
      timeout: 10s
      retries: 10
    tty: true
    volumes:
      - '$PWD/volume/rabbitmq/data:/data'
volumes:
  rabbitmq_data:
    driver: local
